{{- if and .Values.mosquitto.persistence.enabled (not .Values.mosquitto.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.mosquitto.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mosquitto.persistence.size | quote }}
  {{- if .Values.mosquitto.persistence.storageClass }}
  {{- if (eq "-" .Values.mosquitto.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.mosquitto.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  {{- if or .Values.mosquitto.persistence.matchLabels (.Values.mosquitto.persistence.matchExpressions) }}
  selector:
  {{- if .Values.mosquitto.persistence.matchLabels }}
    matchLabels:
{{ toYaml .Values.mosquitto.persistence.matchLabels | indent 8 }}
  {{- end -}}
  {{- if .Values.mosquitto.persistence.matchExpressions }}
    matchExpressions:
{{ toYaml .Values.mosquitto.persistence.matchExpressions | indent 8 }}
  {{- end -}}
  {{- end }}
{{- end -}}
